name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10.14.0'
          
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Lint
        run: pnpm lint
        
      - name: Type check
        run: pnpm run type-check || true
        
      - name: Build packages
        run: pnpm build
        
      - name: Run tests
        run: pnpm test

  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10.14.0'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build contracts
        run: pnpm --filter @neuronetiq/marketplace-contracts build
        
      - name: Build web app
        run: pnpm --filter marketplace-web build
        env:
          NEXT_PUBLIC_MP_BASE: https://marketplace.neuronetiq.com

  build-template:
    name: Build RunPod Template
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10.14.0'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build contracts
        run: pnpm --filter @neuronetiq/marketplace-contracts build
        
      - name: Build template
        run: pnpm --filter runpod-signal-http build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: templates/runpod-signal-http
          push: false
          tags: runpod-signal-http:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
